# Ameba configuration
# Documentation: https://github.com/crystal-ameba/ameba

Excluded:
  - examples/demo_app/lib/**/*.cr
  - examples/jqcp_demo/lib/**/*.cr

Documentation/DocumentationAdmonition:
  Enabled: false
